spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
server:
  port: 8082